"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AuthorAttribution } from "./AuthorAttribution";
import { RateProjectFeedback } from "./RateProjectFeedback";
import { ThemeToggle } from "./ThemeToggle";
import { JobInput } from "./JobInput";
import { ResumeInput } from "./ResumeInput";
import { SuggestionsPanel } from "./SuggestionsPanel";
import { LatexCvPanel } from "./LatexCvPanel";
import { extractTextFromFile } from "@/lib/extractText";
import { AUTHOR, PROJECT_NAME, PROJECT_TAGLINE } from "@/lib/projectMeta";
import { combineMatches, extractJobSkills, keywordMatch, matchPercentage } from "@/lib/skills";
import { generateBulletSuggestion, semanticScoresForSkills } from "@/lib/matchResume";
import {
  DEFAULT_LATEX_TEMPLATE,
  buildFinalOptimizedCvPrompt,
  buildLatexCvPrompt,
  buildSelectionImprovePrompt,
  buildWholeResumePrompt,
  sanitizeCvSuggestionOutput,
  sanitizeLatexModelOutput,
} from "@/lib/resumeBullets";

type WizardStep = 0 | 1 | 2 | 3 | 4;

const STEP_TOTAL = 5;

function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function Dashboard() {
  const [step, setStep] = useState<WizardStep>(0);
  const [direction, setDirection] = useState(1);
  const [navLoading, setNavLoading] = useState(false);

  const [resumeText, setResumeText] = useState("");
  const [resumeFileName, setResumeFileName] = useState<string | null>(null);
  const [resumeLoading, setResumeLoading] = useState(false);
  const [resumeError, setResumeError] = useState<string | null>(null);
  const [resumePdfUrl, setResumePdfUrl] = useState<string | null>(null);
  const resumePdfUrlRef = useRef<string | null>(null);

  const updateResumePdfUrl = useCallback((next: string | null) => {
    if (resumePdfUrlRef.current) {
      URL.revokeObjectURL(resumePdfUrlRef.current);
    }
    resumePdfUrlRef.current = next;
    setResumePdfUrl(next);
  }, []);

  useEffect(() => {
    return () => {
      if (resumePdfUrlRef.current) {
        URL.revokeObjectURL(resumePdfUrlRef.current);
        resumePdfUrlRef.current = null;
      }
    };
  }, []);

  const [jobDescriptionText, setJobDescriptionText] = useState("");
  const [jobTitle, setJobTitle] = useState<string | null>(null);
  const [jobView, setJobView] = useState<"edit" | "preview">("edit");
  const [linkedInLoading, setLinkedInLoading] = useState(false);
  const [jobError, setJobError] = useState<string | null>(null);

  const [matchPct, setMatchPct] = useState(0);

  const [cvSuggestion, setCvSuggestion] = useState("");
  const [suggestionLoading, setSuggestionLoading] = useState(false);
  const [suggestionError, setSuggestionError] = useState<string | null>(null);

  const [finalCv, setFinalCv] = useState("");
  const [finalError, setFinalError] = useState<string | null>(null);
  const [latexCode, setLatexCode] = useState(DEFAULT_LATEX_TEMPLATE);
  const [latexLoading, setLatexLoading] = useState(false);
  const [latexError, setLatexError] = useState<string | null>(null);

  const autoGeneratedStep4Ref = useRef(false);
  const autoGeneratedLatexRef = useRef(false);

  const goToStep = useCallback(
    (next: WizardStep) => {
      setDirection(next > step ? 1 : -1);
      setStep(next);
    },
    [step],
  );

  const canGoNext = useMemo(() => {
    if (step === 0) return true;
    if (step === 1) return resumeText.trim().length > 0 && !resumeLoading;
    if (step === 2) return jobDescriptionText.trim().length > 0 && !linkedInLoading;
    if (step === 3) return true;
    return false;
  }, [jobDescriptionText, linkedInLoading, resumeLoading, resumeText, step]);

  const stepCtaLabel = useMemo(() => {
    if (step === 0) return "Get Started";
    if (step === 1) return "Next";
    if (step === 2) return "Next";
    if (step === 3) return "Continue to LaTeX";
    return "Completed";
  }, [step]);

  const onResumeFile = useCallback(async (file: File) => {
    setResumeLoading(true);
    setResumeError(null);
    const isPdf = /\.pdf$/i.test(file.name) || file.type === "application/pdf";
    try {
      const text = await extractTextFromFile(file);
      setResumeText(text);
      setResumeFileName(file.name);
      if (isPdf) {
        updateResumePdfUrl(URL.createObjectURL(file));
      } else {
        updateResumePdfUrl(null);
      }
    } catch (e) {
      updateResumePdfUrl(null);
      setResumeError(e instanceof Error ? e.message : "Could not read file.");
    } finally {
      setResumeLoading(false);
    }
  }, [updateResumePdfUrl]);

  const onChangeCv = useCallback(() => {
    updateResumePdfUrl(null);
    setResumeText("");
    setResumeFileName(null);
    setResumeError(null);
  }, [updateResumePdfUrl]);

  const onJobFile = useCallback(async (file: File) => {
    setJobError(null);
    try {
      const text = await extractTextFromFile(file);
      setJobDescriptionText(text);
      setJobTitle(null);
    } catch (e) {
      setJobError(e instanceof Error ? e.message : "Could not read file.");
    }
  }, []);

  const onLinkedInFetch = useCallback(async (url: string) => {
    setJobError(null);
    setLinkedInLoading(true);
    try {
      const res = await fetch("/api/linkedin-job", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });
      const data = (await res.json()) as { error?: string; text?: string; title?: string | null };
      if (!res.ok || !data.text?.trim()) {
        throw new Error(data.error ?? "Could not load job from that URL.");
      }
      setJobDescriptionText(data.text.trim());
      setJobTitle(data.title?.trim() || null);
    } catch (e) {
      setJobError(e instanceof Error ? e.message : "Failed to fetch job.");
    } finally {
      setLinkedInLoading(false);
    }
  }, []);

  const runAnalysisFor = useCallback(async (resume: string, job: string) => {
    if (!resume.trim() || !job.trim()) return;

    const resumeNorm = resume.toLowerCase();
    const skills = extractJobSkills(job);
    const keywordFlags = skills.map((s) => keywordMatch(resumeNorm, s));

    let semanticScores: (number | null)[] = skills.map(() => null);
    try {
      semanticScores = await semanticScoresForSkills(resume, skills);
    } catch {
      semanticScores = skills.map(() => null);
    }

    const combined = combineMatches(skills, keywordFlags, semanticScores);
    setMatchPct(matchPercentage(combined));
  }, []);

  const generateSuggestionsFor = useCallback(async (resume: string, job: string) => {
    if (!resume.trim() || !job.trim()) return;
    setSuggestionError(null);
    setSuggestionLoading(true);
    try {
      const prompt = buildWholeResumePrompt(job, resume);
      const text = await generateBulletSuggestion(prompt);
      setCvSuggestion(sanitizeCvSuggestionOutput(text));
    } catch (e) {
      setSuggestionError(e instanceof Error ? e.message : "Could not generate CV suggestions.");
    } finally {
      setSuggestionLoading(false);
    }
  }, []);

  const onImproveSelection = useCallback(
    async (selectedText: string, instruction: string) => {
      if (!jobDescriptionText.trim()) {
        throw new Error("No job description context is loaded yet.");
      }
      if (!cvSuggestion.trim()) {
        throw new Error("Generate suggestions first, then select text to improve.");
      }
      const prompt = buildSelectionImprovePrompt(
        jobDescriptionText,
        cvSuggestion,
        selectedText,
        instruction,
      );
      const improved = await generateBulletSuggestion(prompt);
      return sanitizeCvSuggestionOutput(improved);
    },
    [cvSuggestion, jobDescriptionText],
  );

  const generateFinalCv = useCallback(async () => {
    if (!resumeText.trim() || !jobDescriptionText.trim()) {
      setFinalError("Resume and job description are required before final generation.");
      return;
    }
    setFinalError(null);
    try {
      const prompt = buildFinalOptimizedCvPrompt(jobDescriptionText, resumeText, cvSuggestion);
      const text = await generateBulletSuggestion(prompt);
      setFinalCv(sanitizeCvSuggestionOutput(text));
    } catch (e) {
      setFinalError(e instanceof Error ? e.message : "Could not generate optimized CV.");
    }
  }, [cvSuggestion, jobDescriptionText, resumeText]);

  const generateLatexCv = useCallback(async () => {
    if (!jobDescriptionText.trim()) {
      setLatexError("Job description is required before LaTeX generation.");
      return;
    }
    const sourceResume = finalCv.trim() || cvSuggestion.trim() || resumeText.trim();
    if (!sourceResume) {
      setLatexError("Resume content is required before LaTeX generation.");
      return;
    }
    setLatexError(null);
    setLatexLoading(true);
    try {
      const prompt = buildLatexCvPrompt(jobDescriptionText, sourceResume);
      const text = await generateBulletSuggestion(prompt);
      setLatexCode(sanitizeLatexModelOutput(text.replace(/\r\n/g, "\n")));
    } catch (e) {
      setLatexError(e instanceof Error ? e.message : "Could not generate LaTeX CV.");
    } finally {
      setLatexLoading(false);
    }
  }, [cvSuggestion, finalCv, jobDescriptionText, resumeText]);

  const downloadLatexTex = useCallback(() => {
    if (!latexCode.trim()) return;
    const content = latexCode.endsWith("\n") ? latexCode : `${latexCode}\n`;
    downloadText(content, "optimized-cv.tex");
  }, [latexCode]);

  const onNext = useCallback(async () => {
    if (!canGoNext || navLoading) return;

    if (step === 0) {
      goToStep(1);
      return;
    }
    if (step === 1) {
      goToStep(2);
      return;
    }
    if (step === 2) {
      setNavLoading(true);
      try {
        await runAnalysisFor(resumeText, jobDescriptionText);
        autoGeneratedStep4Ref.current = false;
        goToStep(3);
      } finally {
        setNavLoading(false);
      }
      return;
    }
    if (step === 3) {
      setNavLoading(true);
      await generateFinalCv();
      setNavLoading(false);
      goToStep(4);
    }
  }, [canGoNext, generateFinalCv, goToStep, jobDescriptionText, navLoading, resumeText, runAnalysisFor, step]);

  const onBack = useCallback(() => {
    if (navLoading) return;
    if (step > 0) goToStep((step - 1) as WizardStep);
  }, [goToStep, navLoading, step]);

  useEffect(() => {
    if (step !== 3) return;
    if (autoGeneratedStep4Ref.current) return;
    if (!resumeText.trim() || !jobDescriptionText.trim()) return;
    autoGeneratedStep4Ref.current = true;
    void generateSuggestionsFor(resumeText, jobDescriptionText);
  }, [generateSuggestionsFor, jobDescriptionText, resumeText, step]);

  useEffect(() => {
    if (step !== 4) {
      autoGeneratedLatexRef.current = false;
      return;
    }
    if (autoGeneratedLatexRef.current) return;
    if (!jobDescriptionText.trim()) return;
    const sourceResume = finalCv.trim() || cvSuggestion.trim() || resumeText.trim();
    if (!sourceResume) return;
    autoGeneratedLatexRef.current = true;
    void generateLatexCv();
  }, [cvSuggestion, finalCv, generateLatexCv, jobDescriptionText, resumeText, step]);

  const stepIndicator = `${step + 1} of ${STEP_TOTAL}`;

  return (
    <div className="relative min-h-screen overflow-hidden bg-slate-50 text-slate-900 dark:bg-[#0a0a0f] dark:text-zinc-100">
      <div className="pointer-events-none absolute inset-0 opacity-100 [background:radial-gradient(900px_500px_at_10%_-10%,rgba(6,182,212,0.14),transparent_50%),radial-gradient(900px_500px_at_90%_-10%,rgba(59,130,246,0.1),transparent_50%),linear-gradient(180deg,#f8fafc_0%,#f1f5f9_100%)] dark:opacity-70 dark:[background:radial-gradient(900px_500px_at_10%_-10%,rgba(45,212,191,0.2),transparent_50%),radial-gradient(900px_500px_at_90%_-10%,rgba(59,130,246,0.16),transparent_50%),linear-gradient(180deg,#0a0a0f_0%,#090b14_100%)]" />
      <div className="pointer-events-none absolute inset-0 opacity-[0.35] [background-image:linear-gradient(rgba(15,23,42,0.07)_1px,transparent_1px),linear-gradient(90deg,rgba(15,23,42,0.07)_1px,transparent_1px)] [background-size:28px_28px] dark:opacity-[0.06] dark:[background-image:linear-gradient(rgba(255,255,255,.7)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.7)_1px,transparent_1px)]" />

      <div className="relative mx-auto flex h-screen w-full max-w-6xl flex-col px-6 pb-28 pt-8">
        <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between sm:gap-3">
          <div className="min-w-0">
            <p className="text-xs uppercase tracking-[0.25em] text-cyan-700/90 dark:text-cyan-300/80">{PROJECT_NAME}</p>
            <AuthorAttribution variant="compact" className="mt-1.5 max-w-xl" />
          </div>
          <div className="flex shrink-0 items-center gap-2 self-end sm:self-start">
            <RateProjectFeedback />
            <ThemeToggle />
          </div>
        </div>

        <div className="relative flex-1 overflow-hidden">
          <AnimatePresence mode="wait" custom={direction} initial={false}>
            <motion.section
              key={step}
              custom={direction}
              initial={{ x: direction > 0 ? 56 : -56, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: direction > 0 ? -56 : 56, opacity: 0 }}
              transition={{ duration: 0.34, ease: [0.22, 1, 0.36, 1] }}
              className="h-full overflow-y-auto pr-1"
            >
              {step === 0 && (
                <div className="flex h-full min-h-[50vh] items-center justify-center">
                  <div className="w-full max-w-4xl rounded-3xl border border-slate-200/90 bg-white/80 p-10 shadow-xl shadow-slate-200/50 backdrop-blur-xl dark:border-white/10 dark:bg-white/[0.03] dark:shadow-none">
                    <p className="mb-4 inline-flex rounded-full border border-cyan-500/35 bg-cyan-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-cyan-700 dark:border-cyan-400/40 dark:bg-cyan-400/10 dark:text-cyan-300">
                      Premium Guided Flow
                    </p>
                    <p className="mb-3 text-2xl font-semibold tracking-tight text-cyan-800 dark:text-cyan-200 sm:text-3xl">
                      {PROJECT_NAME}
                    </p>
                    <h1 className="text-5xl font-semibold tracking-tight text-slate-900 sm:text-6xl dark:text-white">
                      Build a role-optimized CV in minutes.
                    </h1>
                    <p className="mt-3 text-base font-medium text-slate-500 dark:text-zinc-400">{PROJECT_TAGLINE}</p>
                    <p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-600 dark:text-zinc-300">
                      A guided five-step experience: add your CV, paste or fetch a job posting, get AI improvements, and
                      export a polished LaTeX CV with confidence.
                    </p>
                    <div className="mt-10 flex items-center gap-3 text-sm text-slate-500 dark:text-zinc-400">
                      <span className="h-2 w-2 animate-pulse rounded-full bg-cyan-500 dark:bg-cyan-300" />
                      Cutting-edge workflow. Zero clutter. Linear and focused.
                    </div>
                  </div>
                </div>
              )}

              {step === 1 && (
                <div className="mx-auto flex min-h-full w-full max-w-3xl flex-col justify-center py-4">
                  <h2 className="text-3xl font-semibold text-slate-900 dark:text-white">Upload your CV</h2>
                  <p className="mt-2 text-slate-600 dark:text-zinc-400">
                    Upload or paste your CV. After it loads you can review it or use Change CV to start over.
                  </p>
                  <div className="mt-8">
                    <ResumeInput
                      value={resumeText}
                      onChange={setResumeText}
                      onFile={onResumeFile}
                      onChangeCv={onChangeCv}
                      disabled={navLoading}
                      loading={resumeLoading}
                      parseError={resumeError}
                      uploadedLabel={resumeFileName}
                      pdfObjectUrl={resumePdfUrl}
                    />
                  </div>
                </div>
              )}

              {step === 2 && (
                <div className="mx-auto flex min-h-full w-full max-w-4xl flex-col py-4">
                  <h2 className="text-3xl font-semibold text-slate-900 dark:text-white">Job description</h2>
                  <p className="mt-2 text-slate-600 dark:text-zinc-400">
                    Paste the posting, upload a .txt file, or fetch from a LinkedIn job URL.
                  </p>
                  <div className="mt-6">
                    <JobInput
                      value={jobDescriptionText}
                      onChange={setJobDescriptionText}
                      onFile={onJobFile}
                      disabled={navLoading}
                      linkedInLoading={linkedInLoading}
                      linkedInError={jobError}
                      onLinkedInFetch={onLinkedInFetch}
                      jobTitle={jobTitle}
                      jobView={jobView}
                      onJobViewChange={setJobView}
                    />
                  </div>
                </div>
              )}

              {step === 3 && (
                <div className="mx-auto flex min-h-full w-full max-w-5xl flex-col py-4">
                  <div className="mb-5 flex items-end justify-between">
                    <div>
                      <h2 className="text-3xl font-semibold text-slate-900 dark:text-white">CV improvement suggestions</h2>
                      <p className="mt-2 text-slate-600 dark:text-zinc-400">
                        Suggestions use your job description as context. Highlight lines to improve specific parts.
                      </p>
                    </div>
                    {matchPct > 0 && (
                      <p className="rounded-full border border-cyan-200 bg-cyan-50 px-3 py-1 text-sm font-medium text-cyan-900 dark:border-cyan-300/40 dark:bg-cyan-300/10 dark:text-cyan-200">
                        Skill Match: {matchPct}%
                      </p>
                    )}
                  </div>

                  <div className="rounded-2xl border border-slate-200/90 bg-white/90 p-4 shadow-sm dark:border-white/10 dark:bg-white/[0.03] dark:shadow-none">
                    <SuggestionsPanel
                      resumeText={resumeText}
                      suggestion={cvSuggestion}
                      onChangeSuggestion={setCvSuggestion}
                      onGenerate={() => void generateSuggestionsFor(resumeText, jobDescriptionText)}
                      onImproveSelection={onImproveSelection}
                      onDownload={() => downloadText(cvSuggestion, "cv-suggestions.txt")}
                      loading={suggestionLoading}
                      error={suggestionError}
                    />
                  </div>
                </div>
              )}

              {step === 4 && (
                <div className="mx-auto flex min-h-full w-full max-w-5xl flex-col py-4">
                  <p className="mb-4 text-sm text-slate-600 dark:text-zinc-400">
                    Your text CV was refined in the previous step. Here you can generate LaTeX, preview it, and download{" "}
                    <span className="font-medium text-slate-800 dark:text-zinc-200">.tex</span>.
                  </p>
                  {finalError && (
                    <p className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-800 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-100">
                      {finalError}
                    </p>
                  )}
                  <LatexCvPanel
                    latexCode={latexCode}
                    onChangeLatex={setLatexCode}
                    onGenerateLatex={() => void generateLatexCv()}
                    onDownloadTex={downloadLatexTex}
                    loading={latexLoading}
                    error={latexError}
                  />
                </div>
              )}
            </motion.section>
          </AnimatePresence>
        </div>
      </div>

      <div className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200/90 bg-white/85 backdrop-blur-xl dark:border-white/10 dark:bg-[#0b0d16]/90">
        <div className="mx-auto flex w-full max-w-6xl flex-col gap-2 px-6 py-3 sm:flex-row sm:items-center sm:justify-between sm:gap-4 sm:py-4">
          <div className="min-w-0">
            <div className="text-sm text-slate-600 dark:text-zinc-300">
              Step <span className="font-semibold text-slate-900 dark:text-white">{stepIndicator}</span>
            </div>
            <AuthorAttribution variant="compact" className="mt-1.5 max-w-md" />
          </div>
          <div className="flex shrink-0 items-center gap-3">
            {step >= 1 && (
              <button
                type="button"
                onClick={onBack}
                disabled={navLoading}
                className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 shadow-sm transition hover:bg-slate-50 disabled:opacity-60 dark:border-white/20 dark:bg-transparent dark:text-zinc-200 dark:shadow-none dark:hover:bg-white/10"
              >
                Back
              </button>
            )}
            {step < STEP_TOTAL - 1 ? (
              <button
                type="button"
                onClick={() => void onNext()}
                disabled={!canGoNext || navLoading}
                className="rounded-xl bg-cyan-600 px-5 py-2 text-sm font-semibold text-white shadow-md shadow-cyan-600/25 transition hover:bg-cyan-500 disabled:opacity-50 dark:bg-cyan-400 dark:text-slate-950 dark:shadow-none dark:hover:bg-cyan-300"
              >
                {navLoading ? "Working…" : stepCtaLabel}
              </button>
            ) : (
              <button
                type="button"
                onClick={() => goToStep(0)}
                className="rounded-xl border border-emerald-300/80 bg-emerald-50 px-5 py-2 text-sm font-semibold text-emerald-900 transition hover:bg-emerald-100 dark:border-emerald-300/40 dark:bg-emerald-300/10 dark:text-emerald-200 dark:hover:bg-emerald-300/20"
              >
                Start Over
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
